$installation = <<SCRIPT
sed -i 's/GRUB_CMDLINE_LINUX=""/GRUB_CMDLINE_LINUX="cgroup_enable=memory swapaccount=1"/g' /etc/default/grub
update-grub
echo "Europe/Amsterdam" | tee /etc/timezone
dpkg-reconfigure --frontend noninteractive tzdata

useradd dev -m
echo dev:dev | /usr/sbin/chpasswd
usermod -G sudo dev
usermod -s /bin/bash dev
mkdir -p /home/dev/.ssh
echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDVZbKDrYnRDEkDjvUUt2NcmRhrQAQh0W9ZeW1gNrZ3vE7q38zOzzpg8W1tovRfVu2nVznybEWtx/3rsJnRauzP3GVgzbKJY1g8YwRwQw6gSJYNtkwfaO2AfkAVWO3r378EH//xD2O4bJ3xwWTrr7aXIQGEoAcHBFGlAko0nWwn13VTa6Hp5cZULi+qgGKaQTSJHQ+jvP8puf7efbLs1bHsxCXUn72aFdeyDGS0F9MuIeyZneHVpwKtmKWZXAoac9E7zdeiSiV+vq4YBLmntQoC0uHYuQ9w1uyw0+QeO6fE05vMuSzrO5eWShCeXJPAOMwfPv6xt3+Pb/n9FBIkCWqH jvermeir@hotmail.com" >> /home/dev/.ssh/authorized_keys
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9

sudo apt-get remove docker docker-engine docker.io
sudo apt-get update
sudo apt-get install \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common
sudo apt install  openjdk-8-jdk-headless \
    maven
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo apt-key fingerprint 0EBFCD88
sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"
sudo apt-get update
sudo apt-get install docker-ce -y
sudo curl -L https://github.com/docker/compose/releases/download/1.17.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
SCRIPT

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.hostname = 'docker.localdomain'
  config.vm.network 'private_network', ip: '192.168.99.101'
  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    v.gui = true
    v.name = "microServicesDev"
    v.customize ['modifyvm', :id, '--memory', 2024]
  end

  config.vm.provision 'shell', inline: $installation
end
